export const countries = [
  {
    name: 'United States',
    code: '+1',
    flag: 'https://flagcdn.com/us.svg',
    allowedLengths: [10],
  },
  {
    name: 'Canada',
    code: '+1',
    flag: 'https://flagcdn.com/ca.svg',
    allowedLengths: [10],
  },
  {
    name: 'United Kingdom',
    code: '+44',
    flag: 'https://flagcdn.com/gb.svg',
    allowedLengths: [10],
  },
  {
    name: 'Australia',
    code: '+61',
    flag: 'https://flagcdn.com/au.svg',
    allowedLengths: [9],
  },
  {
    name: 'Afghanistan',
    code: '+93',
    flag: 'https://flagcdn.com/af.svg',
    allowedLengths: [9],
  },
  {
    name: 'Albania',
    code: '+355',
    flag: 'https://flagcdn.com/al.svg',
    allowedLengths: [9],
  },
  {
    name: 'Algeria',
    code: '+213',
    flag: 'https://flagcdn.com/dz.svg',
    allowedLengths: [9],
  },
  {
    name: 'Andorra',
    code: '+376',
    flag: 'https://flagcdn.com/ad.svg',
    allowedLengths: [6],
  },
  {
    name: 'Angola',
    code: '+244',
    flag: 'https://flagcdn.com/ao.svg',
    allowedLengths: [9],
  },
  {
    name: 'Antigua and Barbuda',
    code: '+1268',
    flag: 'https://flagcdn.com/ag.svg',
    allowedLengths: [10],
  },
  {
    name: 'Argentina',
    code: '+54',
    flag: 'https://flagcdn.com/ar.svg',
    allowedLengths: [10],
  },
  {
    name: 'Armenia',
    code: '+374',
    flag: 'https://flagcdn.com/am.svg',
    allowedLengths: [8],
  },
  {
    name: 'Austria',
    code: '+43',
    flag: 'https://flagcdn.com/at.svg',
    allowedLengths: [10, 11],
  },
  {
    name: 'Azerbaijan',
    code: '+994',
    flag: 'https://flagcdn.com/az.svg',
    allowedLengths: [9],
  },
  {
    name: 'Bahamas',
    code: '+1242',
    flag: 'https://flagcdn.com/bs.svg',
    allowedLengths: [10],
  },
  {
    name: 'Bahrain',
    code: '+973',
    flag: 'https://flagcdn.com/bh.svg',
    allowedLengths: [8],
  },
  {
    name: 'Bangladesh',
    code: '+880',
    flag: 'https://flagcdn.com/bd.svg',
    allowedLengths: [10],
  },
  {
    name: 'Barbados',
    code: '+1246',
    flag: 'https://flagcdn.com/bb.svg',
    allowedLengths: [10],
  },
  {
    name: 'Belarus',
    code: '+375',
    flag: 'https://flagcdn.com/by.svg',
    allowedLengths: [9],
  },
  {
    name: 'Belgium',
    code: '+32',
    flag: 'https://flagcdn.com/be.svg',
    allowedLengths: [9],
  },
  {
    name: 'Belize',
    code: '+501',
    flag: 'https://flagcdn.com/bz.svg',
    allowedLengths: [7],
  },
  {
    name: 'Benin',
    code: '+229',
    flag: 'https://flagcdn.com/bj.svg',
    allowedLengths: [8],
  },
  {
    name: 'Bhutan',
    code: '+975',
    flag: 'https://flagcdn.com/bt.svg',
    allowedLengths: [8],
  },
  {
    name: 'Bolivia',
    code: '+591',
    flag: 'https://flagcdn.com/bo.svg',
    allowedLengths: [8],
  },
  {
    name: 'Bosnia and Herzegovina',
    code: '+387',
    flag: 'https://flagcdn.com/ba.svg',
    allowedLengths: [8, 9],
  },
  {
    name: 'Botswana',
    code: '+267',
    flag: 'https://flagcdn.com/bw.svg',
    allowedLengths: [7, 8],
  },
  {
    name: 'Brazil',
    code: '+55',
    flag: 'https://flagcdn.com/br.svg',
    allowedLengths: [10, 11],
  },
  {
    name: 'Brunei',
    code: '+673',
    flag: 'https://flagcdn.com/bn.svg',
    allowedLengths: [7],
  },
  {
    name: 'Bulgaria',
    code: '+359',
    flag: 'https://flagcdn.com/bg.svg',
    allowedLengths: [9],
  },
  {
    name: 'Burkina Faso',
    code: '+226',
    flag: 'https://flagcdn.com/bf.svg',
    allowedLengths: [8],
  },
  {
    name: 'Burundi',
    code: '+257',
    flag: 'https://flagcdn.com/bi.svg',
    allowedLengths: [8],
  },
  {
    name: 'Cambodia',
    code: '+855',
    flag: 'https://flagcdn.com/kh.svg',
    allowedLengths: [9],
  },
  {
    name: 'Cameroon',
    code: '+237',
    flag: 'https://flagcdn.com/cm.svg',
    allowedLengths: [9],
  },
  {
    name: 'Cape Verde',
    code: '+238',
    flag: 'https://flagcdn.com/cv.svg',
    allowedLengths: [7],
  },
  {
    name: 'Chile',
    code: '+56',
    flag: 'https://flagcdn.com/cl.svg',
    allowedLengths: [9],
  },
  {
    name: 'China',
    code: '+86',
    flag: 'https://flagcdn.com/cn.svg',
    allowedLengths: [11],
  },
  {
    name: 'Colombia',
    code: '+57',
    flag: 'https://flagcdn.com/co.svg',
    allowedLengths: [10],
  },
  {
    name: 'Costa Rica',
    code: '+506',
    flag: 'https://flagcdn.com/cr.svg',
    allowedLengths: [8],
  },
  {
    name: 'Croatia',
    code: '+385',
    flag: 'https://flagcdn.com/hr.svg',
    allowedLengths: [9],
  },
  {
    name: 'Cuba',
    code: '+53',
    flag: 'https://flagcdn.com/cu.svg',
    allowedLengths: [8],
  },
  {
    name: 'Cyprus',
    code: '+357',
    flag: 'https://flagcdn.com/cy.svg',
    allowedLengths: [8],
  },
  {
    name: 'Czech Republic',
    code: '+420',
    flag: 'https://flagcdn.com/cz.svg',
    allowedLengths: [9],
  },
  {
    name: 'Democratic Republic of the Congo',
    code: '+243',
    flag: 'https://flagcdn.com/cd.svg',
    allowedLengths: [9],
  },
  {
    name: 'Denmark',
    code: '+45',
    flag: 'https://flagcdn.com/dk.svg',
    allowedLengths: [8],
  },
  {
    name: 'Djibouti',
    code: '+253',
    flag: 'https://flagcdn.com/dj.svg',
    allowedLengths: [6],
  },
  {
    name: 'Dominican Republic',
    code: '+1-809',
    flag: 'https://flagcdn.com/do.svg',
    allowedLengths: [10],
  },
  {
    name: 'Ecuador',
    code: '+593',
    flag: 'https://flagcdn.com/ec.svg',
    allowedLengths: [9],
  },
  {
    name: 'Egypt',
    code: '+20',
    flag: 'https://flagcdn.com/eg.svg',
    allowedLengths: [9, 10],
  },
  {
    name: 'El Salvador',
    code: '+503',
    flag: 'https://flagcdn.com/sv.svg',
    allowedLengths: [8],
  },
  {
    name: 'Estonia',
    code: '+372',
    flag: 'https://flagcdn.com/ee.svg',
    allowedLengths: [7, 8],
  },
  {
    name: 'Eswatini',
    code: '+268',
    flag: 'https://flagcdn.com/sz.svg',
    allowedLengths: [8],
  },
  {
    name: 'Ethiopia',
    code: '+251',
    flag: 'https://flagcdn.com/et.svg',
    allowedLengths: [9],
  },
  {
    name: 'Finland',
    code: '+358',
    flag: 'https://flagcdn.com/fi.svg',
    allowedLengths: [10],
  },
  {
    name: 'France',
    code: '+33',
    flag: 'https://flagcdn.com/fr.svg',
    allowedLengths: [9],
  },
  {
    name: 'Germany',
    code: '+49',
    flag: 'https://flagcdn.com/de.svg',
    allowedLengths: [10, 11],
  },
  {
    name: 'Georgia',
    code: '+995',
    flag: 'https://flagcdn.com/ge.svg',
    allowedLengths: [9, 10],
  },
  {
    name: 'Ghana',
    code: '+233',
    flag: 'https://flagcdn.com/gh.svg',
    allowedLengths: [9],
  },
  {
    name: 'Greece',
    code: '+30',
    flag: 'https://flagcdn.com/gr.svg',
    allowedLengths: [10],
  },
  {
    name: 'Greenland',
    code: '+299',
    flag: 'https://flagcdn.com/gl.svg',
    allowedLengths: [6],
  },
  {
    name: 'Guatemala',
    code: '+502',
    flag: 'https://flagcdn.com/gt.svg',
    allowedLengths: [8],
  },
  {
    name: 'Guinea',
    code: '+224',
    flag: 'https://flagcdn.com/gn.svg',
    allowedLengths: [9],
  },
  {
    name: 'Haiti',
    code: '+509',
    flag: 'https://flagcdn.com/ht.svg',
    allowedLengths: [8],
  },
  {
    name: 'Honduras',
    code: '+504',
    flag: 'https://flagcdn.com/hn.svg',
    allowedLengths: [8],
  },
  {
    name: 'Hong Kong',
    code: '+852',
    flag: 'https://flagcdn.com/hk.svg',
    allowedLengths: [8],
  },
  {
    name: 'Hungary',
    code: '+36',
    flag: 'https://flagcdn.com/hu.svg',
    allowedLengths: [9],
  },
  {
    name: 'Iceland',
    code: '+354',
    flag: 'https://flagcdn.com/is.svg',
    allowedLengths: [7],
  },
  {
    name: 'India',
    code: '+91',
    flag: 'https://flagcdn.com/in.svg',
    allowedLengths: [10],
  },
  {
    name: 'Indonesia',
    code: '+62',
    flag: 'https://flagcdn.com/id.svg',
    allowedLengths: [10, 11, 12],
  },
  {
    name: 'Iran',
    code: '+98',
    flag: 'https://flagcdn.com/ir.svg',
    allowedLengths: [10],
  },
  {
    name: 'Iraq',
    code: '+964',
    flag: 'https://flagcdn.com/iq.svg',
    allowedLengths: [10],
  },
  {
    name: 'Ireland',
    code: '+353',
    flag: 'https://flagcdn.com/ie.svg',
    allowedLengths: [9],
  },
  {
    name: 'Israel',
    code: '+972',
    flag: 'https://flagcdn.com/il.svg',
    allowedLengths: [9],
  },
  {
    name: 'Italy',
    code: '+39',
    flag: 'https://flagcdn.com/it.svg',
    allowedLengths: [10],
  },
  {
    name: 'Ivory Coast',
    code: '+225',
    flag: 'https://flagcdn.com/ci.svg',
    allowedLengths: [8],
  },
  {
    name: 'Jamaica',
    code: '+1-876',
    flag: 'https://flagcdn.com/jm.svg',
    allowedLengths: [10],
  },
  {
    name: 'Japan',
    code: '+81',
    flag: 'https://flagcdn.com/jp.svg',
    allowedLengths: [10],
  },
  {
    name: 'Jordan',
    code: '+962',
    flag: 'https://flagcdn.com/jo.svg',
    allowedLengths: [9],
  },
  {
    name: 'Kazakhstan',
    code: '+7',
    flag: 'https://flagcdn.com/kz.svg',
    allowedLengths: [10],
  },
  {
    name: 'Kenya',
    code: '+254',
    flag: 'https://flagcdn.com/ke.svg',
    allowedLengths: [9],
  },
  {
    name: 'Kuwait',
    code: '+965',
    flag: 'https://flagcdn.com/kw.svg',
    allowedLengths: [8],
  },
  {
    name: 'Kyrgyzstan',
    code: '+996',
    flag: 'https://flagcdn.com/kg.svg',
    allowedLengths: [9],
  },
  {
    name: 'Laos',
    code: '+856',
    flag: 'https://flagcdn.com/la.svg',
    allowedLengths: [8],
  },
  {
    name: 'Latvia',
    code: '+371',
    flag: 'https://flagcdn.com/lv.svg',
    allowedLengths: [8],
  },
  {
    name: 'Lebanon',
    code: '+961',
    flag: 'https://flagcdn.com/lb.svg',
    allowedLengths: [7, 8],
  },
  {
    name: 'Liechtenstein',
    code: '+423',
    flag: 'https://flagcdn.com/li.svg',
    allowedLengths: [7],
  },
  {
    name: 'Lithuania',
    code: '+370',
    flag: 'https://flagcdn.com/lt.svg',
    allowedLengths: [8],
  },
  {
    name: 'Luxembourg',
    code: '+352',
    flag: 'https://flagcdn.com/lu.svg',
    allowedLengths: [9],
  },
  {
    name: 'Macedonia',
    code: '+389',
    flag: 'https://flagcdn.com/mk.svg',
    allowedLengths: [8],
  },
  {
    name: 'Madagascar',
    code: '+261',
    flag: 'https://flagcdn.com/mg.svg',
    allowedLengths: [9],
  },
  {
    name: 'Malawi',
    code: '+265',
    flag: 'https://flagcdn.com/mw.svg',
    allowedLengths: [9],
  },
  {
    name: 'Malaysia',
    code: '+60',
    flag: 'https://flagcdn.com/my.svg',
    allowedLengths: [9, 10],
  },
  {
    name: 'Maldives',
    code: '+960',
    flag: 'https://flagcdn.com/mv.svg',
    allowedLengths: [7],
  },
  {
    name: 'Mali',
    code: '+223',
    flag: 'https://flagcdn.com/ml.svg',
    allowedLengths: [8],
  },
  {
    name: 'Malta',
    code: '+356',
    flag: 'https://flagcdn.com/mt.svg',
    allowedLengths: [8],
  },
  {
    name: 'Mexico',
    code: '+52',
    flag: 'https://flagcdn.com/mx.svg',
    allowedLengths: [10],
  },
  {
    name: 'Moldova',
    code: '+373',
    flag: 'https://flagcdn.com/md.svg',
    allowedLengths: [8],
  },
  {
    name: 'Monaco',
    code: '+377',
    flag: 'https://flagcdn.com/mc.svg',
    allowedLengths: [8, 9],
  },
  {
    name: 'Mongolia',
    code: '+976',
    flag: 'https://flagcdn.com/mn.svg',
    allowedLengths: [8],
  },
  {
    name: 'Montenegro',
    code: '+382',
    flag: 'https://flagcdn.com/me.svg',
    allowedLengths: [9],
  },
  {
    name: 'Morocco',
    code: '+212',
    flag: 'https://flagcdn.com/ma.svg',
    allowedLengths: [9],
  },
  {
    name: 'Mozambique',
    code: '+258',
    flag: 'https://flagcdn.com/mz.svg',
    allowedLengths: [9],
  },
  {
    name: 'Myanmar',
    code: '+95',
    flag: 'https://flagcdn.com/mm.svg',
    allowedLengths: [9, 10],
  },
  {
    name: 'Namibia',
    code: '+264',
    flag: 'https://flagcdn.com/na.svg',
    allowedLengths: [9],
  },
  {
    name: 'Nepal',
    code: '+977',
    flag: 'https://flagcdn.com/np.svg',
    allowedLengths: [10],
  },
  {
    name: 'Netherlands',
    code: '+31',
    flag: 'https://flagcdn.com/nl.svg',
    allowedLengths: [9],
  },
  {
    name: 'New Zealand',
    code: '+64',
    flag: 'https://flagcdn.com/nz.svg',
    allowedLengths: [8, 9],
  },
  {
    name: 'Nicaragua',
    code: '+505',
    flag: 'https://flagcdn.com/ni.svg',
    allowedLengths: [8],
  },
  {
    name: 'Niger',
    code: '+227',
    flag: 'https://flagcdn.com/ne.svg',
    allowedLengths: [8],
  },
  {
    name: 'Nigeria',
    code: '+234',
    flag: 'https://flagcdn.com/ng.svg',
    allowedLengths: [10],
  },
  {
    name: 'North Korea',
    code: '+850',
    flag: 'https://flagcdn.com/kp.svg',
    allowedLengths: [10],
  },
  {
    name: 'Norway',
    code: '+47',
    flag: 'https://flagcdn.com/no.svg',
    allowedLengths: [8],
  },
  {
    name: 'Oman',
    code: '+968',
    flag: 'https://flagcdn.com/om.svg',
    allowedLengths: [8],
  },
  {
    name: 'Pakistan',
    code: '+92',
    flag: 'https://flagcdn.com/pk.svg',
    allowedLengths: [10],
  },
  {
    name: 'Palestine',
    code: '+970',
    flag: 'https://flagcdn.com/ps.svg',
    allowedLengths: [9],
  },
  {
    name: 'Panama',
    code: '+507',
    flag: 'https://flagcdn.com/pa.svg',
    allowedLengths: [8],
  },
  {
    name: 'Papua New Guinea',
    code: '+675',
    flag: 'https://flagcdn.com/pg.svg',
    allowedLengths: [8],
  },
  {
    name: 'Paraguay',
    code: '+595',
    flag: 'https://flagcdn.com/py.svg',
    allowedLengths: [9],
  },
  {
    name: 'Peru',
    code: '+51',
    flag: 'https://flagcdn.com/pe.svg',
    allowedLengths: [9],
  },
  {
    name: 'Philippines',
    code: '+63',
    flag: 'https://flagcdn.com/ph.svg',
    allowedLengths: [10],
  },
  {
    name: 'Poland',
    code: '+48',
    flag: 'https://flagcdn.com/pl.svg',
    allowedLengths: [9],
  },
  {
    name: 'Portugal',
    code: '+351',
    flag: 'https://flagcdn.com/pt.svg',
    allowedLengths: [9],
  },
  {
    name: 'Puerto Rico',
    code: '+1-787',
    flag: 'https://flagcdn.com/pr.svg',
    allowedLengths: [10],
  },
  {
    name: 'Qatar',
    code: '+974',
    flag: 'https://flagcdn.com/qa.svg',
    allowedLengths: [8],
  },
  {
    name: 'Romania',
    code: '+40',
    flag: 'https://flagcdn.com/ro.svg',
    allowedLengths: [9],
  },
  {
    name: 'Republic of the Congo',
    code: '+242',
    flag: 'https://flagcdn.com/cg.svg',
    allowedLengths: [9],
  },
  {
    name: 'Russia',
    code: '+7',
    flag: 'https://flagcdn.com/ru.svg',
    allowedLengths: [10],
  },
  {
    name: 'Rwanda',
    code: '+250',
    flag: 'https://flagcdn.com/rw.svg',
    allowedLengths: [9],
  },
  {
    name: 'San Marino',
    code: '+378',
    flag: 'https://flagcdn.com/sm.svg',
    allowedLengths: [6],
  },
  {
    name: 'Saudi Arabia',
    code: '+966',
    flag: 'https://flagcdn.com/sa.svg',
    allowedLengths: [9],
  },
  {
    name: 'Senegal',
    code: '+221',
    flag: 'https://flagcdn.com/sn.svg',
    allowedLengths: [9],
  },
  {
    name: 'Serbia',
    code: '+381',
    flag: 'https://flagcdn.com/rs.svg',
    allowedLengths: [9],
  },
  {
    name: 'Sierra Leone',
    code: '+232',
    flag: 'https://flagcdn.com/sl.svg',
    allowedLengths: [8],
  },
  {
    name: 'Singapore',
    code: '+65',
    flag: 'https://flagcdn.com/sg.svg',
    allowedLengths: [8],
  },
  {
    name: 'Slovakia',
    code: '+421',
    flag: 'https://flagcdn.com/sk.svg',
    allowedLengths: [9],
  },
  {
    name: 'Slovenia',
    code: '+386',
    flag: 'https://flagcdn.com/si.svg',
    allowedLengths: [8],
  },
  {
    name: 'Solomon Islands',
    code: '+677',
    flag: 'https://flagcdn.com/sb.svg',
    allowedLengths: [7],
  },
  {
    name: 'Somalia',
    code: '+252',
    flag: 'https://flagcdn.com/so.svg',
    allowedLengths: [9],
  },
  {
    name: 'South Africa',
    code: '+27',
    flag: 'https://flagcdn.com/za.svg',
    allowedLengths: [9],
  },
  {
    name: 'South Korea',
    code: '+82',
    flag: 'https://flagcdn.com/kr.svg',
    allowedLengths: [10],
  },
  {
    name: 'South Sudan',
    code: '+211',
    flag: 'https://flagcdn.com/ss.svg',
    allowedLengths: [9],
  },
  {
    name: 'Spain',
    code: '+34',
    flag: 'https://flagcdn.com/es.svg',
    allowedLengths: [9],
  },
  {
    name: 'Sri Lanka',
    code: '+94',
    flag: 'https://flagcdn.com/lk.svg',
    allowedLengths: [9],
  },
  {
    name: 'Sudan',
    code: '+249',
    flag: 'https://flagcdn.com/sd.svg',
    allowedLengths: [9],
  },
  {
    name: 'Suriname',
    code: '+597',
    flag: 'https://flagcdn.com/sr.svg',
    allowedLengths: [7],
  },
  {
    name: 'Sweden',
    code: '+46',
    flag: 'https://flagcdn.com/se.svg',
    allowedLengths: [9],
  },
  {
    name: 'Switzerland',
    code: '+41',
    flag: 'https://flagcdn.com/ch.svg',
    allowedLengths: [9],
  },
  {
    name: 'Syria',
    code: '+963',
    flag: 'https://flagcdn.com/sy.svg',
    allowedLengths: [9],
  },
  {
    name: 'Taiwan',
    code: '+886',
    flag: 'https://flagcdn.com/tw.svg',
    allowedLengths: [9],
  },
  {
    name: 'Tajikistan',
    code: '+992',
    flag: 'https://flagcdn.com/tj.svg',
    allowedLengths: [9],
  },
  {
    name: 'Tanzania',
    code: '+255',
    flag: 'https://flagcdn.com/tz.svg',
    allowedLengths: [9],
  },
  {
    name: 'Thailand',
    code: '+66',
    flag: 'https://flagcdn.com/th.svg',
    allowedLengths: [9],
  },
  {
    name: 'Timor-Leste',
    code: '+670',
    flag: 'https://flagcdn.com/tl.svg',
    allowedLengths: [8],
  },
  {
    name: 'Togo',
    code: '+228',
    flag: 'https://flagcdn.com/tg.svg',
    allowedLengths: [8],
  },
  {
    name: 'Trinidad and Tobago',
    code: '+1868',
    flag: 'https://flagcdn.com/tt.svg',
    allowedLengths: [10],
  },
  {
    name: 'Tunisia',
    code: '+216',
    flag: 'https://flagcdn.com/tn.svg',
    allowedLengths: [8],
  },
  {
    name: 'Turkey',
    code: '+90',
    flag: 'https://flagcdn.com/tr.svg',
    allowedLengths: [10],
  },
  {
    name: 'Turkmenistan',
    code: '+993',
    flag: 'https://flagcdn.com/tm.svg',
    allowedLengths: [8],
  },
  {
    name: 'Uganda',
    code: '+256',
    flag: 'https://flagcdn.com/ug.svg',
    allowedLengths: [9],
  },
  {
    name: 'Ukraine',
    code: '+380',
    flag: 'https://flagcdn.com/ua.svg',
    allowedLengths: [9],
  },
  {
    name: 'United Arab Emirates',
    code: '+971',
    flag: 'https://flagcdn.com/ae.svg',
    allowedLengths: [9],
  },
  {
    name: 'Uruguay',
    code: '+598',
    flag: 'https://flagcdn.com/uy.svg',
    allowedLengths: [9],
  },
  {
    name: 'Uzbekistan',
    code: '+998',
    flag: 'https://flagcdn.com/uz.svg',
    allowedLengths: [9],
  },
  {
    name: 'Vanuatu',
    code: '+678',
    flag: 'https://flagcdn.com/vu.svg',
    allowedLengths: [7],
  },
  {
    name: 'Vatican City',
    code: '+379',
    flag: 'https://flagcdn.com/va.svg',
    allowedLengths: [10],
  },
  {
    name: 'Venezuela',
    code: '+58',
    flag: 'https://flagcdn.com/ve.svg',
    allowedLengths: [10],
  },
  {
    name: 'Vietnam',
    code: '+84',
    flag: 'https://flagcdn.com/vn.svg',
    allowedLengths: [9],
  },
  {
    name: 'Yemen',
    code: '+967',
    flag: 'https://flagcdn.com/ye.svg',
    allowedLengths: [9],
  },
  {
    name: 'Zambia',
    code: '+260',
    flag: 'https://flagcdn.com/zm.svg',
    allowedLengths: [9],
  },
  {
    name: 'Zimbabwe',
    code: '+263',
    flag: 'https://flagcdn.com/zw.svg',
    allowedLengths: [9],
  },
];

